# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: geocoder.proto for package 'geocoder'

require 'grpc'
require_relative 'geocoder_pb'

module Geocoder
  module GeocoderService
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'geocoder.GeocoderService'

      rpc :Geocode, ::Geocoder::City, ::Geocoder::Coordinates
    end

    Stub = Service.rpc_stub_class
  end
end
